In [135]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
df = pd.read_csv('dataset/city_hour.csv')
df

In [137]:
data = df.dropna(subset=['AQI_Bucket',"AQI"])
data.isnull().sum()

City               0
Datetime           0
PM2.5          31035
PM10          178863
NO             21481
NO2            22267
NOx            51906
NH3           163994
CO             29146
SO2            33058
O3             33372
Benzene        96365
Toluene       149001
Xylene        371700
AQI                0
AQI_Bucket         0
dtype: int64

In [138]:
data = data.ffill()

In [139]:
data = data.bfill()

In [140]:
data

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
680,Ahmedabad,2015-01-29 09:00:00,80.47,84.90,1.42,21.90,20.65,22.83,1.42,32.26,46.71,0.0,0.0,2.07,288.0,Poor
681,Ahmedabad,2015-01-29 10:00:00,87.80,84.90,2.03,19.87,22.22,22.83,2.03,78.95,21.88,0.0,0.0,2.13,181.0,Moderate
682,Ahmedabad,2015-01-29 11:00:00,90.53,84.90,1.72,20.11,22.12,22.83,1.72,95.86,67.67,0.0,0.0,3.45,182.0,Moderate
683,Ahmedabad,2015-01-29 12:00:00,83.53,84.90,0.75,16.35,16.48,22.83,0.75,44.91,88.92,0.0,0.0,3.25,182.0,Moderate
684,Ahmedabad,2015-01-29 13:00:00,68.40,84.90,0.58,13.73,12.50,22.83,0.58,34.57,116.75,0.0,0.0,2.85,179.0,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707870,Visakhapatnam,2020-06-30 20:00:00,9.50,36.00,2.75,25.57,15.85,4.57,0.62,1.85,27.75,0.0,0.0,0.00,51.0,Satisfactory
707871,Visakhapatnam,2020-06-30 21:00:00,17.25,49.25,3.62,33.20,20.62,3.78,0.76,2.02,25.58,0.0,0.0,0.00,51.0,Satisfactory
707872,Visakhapatnam,2020-06-30 22:00:00,36.00,71.00,2.20,30.80,18.20,3.67,0.58,1.77,26.15,0.0,0.0,0.00,50.0,Good
707873,Visakhapatnam,2020-06-30 23:00:00,15.75,63.00,1.02,28.90,16.00,3.80,0.49,0.75,15.82,0.0,0.0,0.00,50.0,Good
707874,Visakhapatnam,2020-07-01 00:00:00,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,0.0,0.0,0.00,50.0,Good

In [141]:
data.isnull().sum()

City          0
Datetime      0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
CO            0
SO2           0
O3            0
Benzene       0
Toluene       0
Xylene        0
AQI           0
AQI_Bucket    0
dtype: int64

In [142]:
data.Benzene.value_counts()

Benzene
0.00      114885
0.22       25772
0.27        8197
0.10        7626
0.03        4209
           ...
436.55         1
438.38         1
442.69         1
473.20         1
138.63         1
Name: count, Length: 5908, dtype: int64

In [145]:
data['Datetime'] = pd.to_datetime(data['Datetime'])

data['Year'] = data['Datetime'].dt.year
data['Month'] = data['Datetime'].dt.month
data['Day'] = data['Datetime'].dt.day
data['Hour'] = data['Datetime'].dt.hour
data['Minute'] = data['Datetime'].dt.minute

data.drop('Datetime', axis=1, inplace=True)

print(data.head())

          City  PM2.5  PM10    NO    NO2    NOx    NH3    CO    SO2      O3  \
680  Ahmedabad  80.47  84.9  1.42  21.90  20.65  22.83  1.42  32.26   46.71
681  Ahmedabad  87.80  84.9  2.03  19.87  22.22  22.83  2.03  78.95   21.88
682  Ahmedabad  90.53  84.9  1.72  20.11  22.12  22.83  1.72  95.86   67.67
683  Ahmedabad  83.53  84.9  0.75  16.35  16.48  22.83  0.75  44.91   88.92
684  Ahmedabad  68.40  84.9  0.58  13.73  12.50  22.83  0.58  34.57  116.75

     Benzene  Toluene  Xylene    AQI AQI_Bucket  Year  Month  Day  Hour  \
680      0.0      0.0    2.07  288.0       Poor  2015      1   29     9
681      0.0      0.0    2.13  181.0   Moderate  2015      1   29    10
682      0.0      0.0    3.45  182.0   Moderate  2015      1   29    11
683      0.0      0.0    3.25  182.0   Moderate  2015      1   29    12
684      0.0      0.0    2.85  179.0   Moderate  2015      1   29    13

     Minute
680       0
681       0
682       0
683       0
684       0

In [146]:
data

,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,Year,Month,Day,Hour,Minute
680,Ahmedabad,80.47,84.90,1.42,21.90,20.65,22.83,1.42,32.26,46.71,0.0,0.0,2.07,288.0,Poor,2015,1,29,9,0
681,Ahmedabad,87.80,84.90,2.03,19.87,22.22,22.83,2.03,78.95,21.88,0.0,0.0,2.13,181.0,Moderate,2015,1,29,10,0
682,Ahmedabad,90.53,84.90,1.72,20.11,22.12,22.83,1.72,95.86,67.67,0.0,0.0,3.45,182.0,Moderate,2015,1,29,11,0
683,Ahmedabad,83.53,84.90,0.75,16.35,16.48,22.83,0.75,44.91,88.92,0.0,0.0,3.25,182.0,Moderate,2015,1,29,12,0
684,Ahmedabad,68.40,84.90,0.58,13.73,12.50,22.83,0.58,34.57,116.75,0.0,0.0,2.85,179.0,Moderate,2015,1,29,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707870,Visakhapatnam,9.50,36.00,2.75,25.57,15.85,4.57,0.62,1.85,27.75,0.0,0.0,0.00,51.0,Satisfactory,2020,6,30,20,0
707871,Visakhapatnam,17.25,49.25,3.62,33.20,20.62,3.78,0.76,2.02,25.58,0.0,0.0,0.00,51.0,Satisfactory,2020,6,30,21,0
707872,Visakhapatnam,36.00,71.00,2.20,30.80,18.20,3.67,0.58,1.77,26.15,0.0,0.0,0.00,50.0,Good,2020,6,30,22,0
707873,Visakhapatnam,15.75,63.00,1.02,28.90,16.00,3.80,0.49,0.75,15.82,0.0,0.0,0.00,50.0,Good,2020,6,30,23,0
707874,Visakhapatnam,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,0.0,0.0,0.00,50.0,Good,2020,7,1,0,0

In [147]:
data.City.value_counts()

City
Delhi                 47694
Bengaluru             45497
Lucknow               44942
Chennai               44649
Hyderabad             44523
Gurugram              33420
Patna                 32318
Ahmedabad             30921
Visakhapatnam         26766
Jaipur                26011
Amritsar              25840
Thiruvananthapuram    24734
Amaravati             19377
Mumbai                18171
Kolkata               18066
Jorapokhar            17430
Brajrajnagar          16047
Talcher               15008
Guwahati              11740
Coimbatore             7610
Chandigarh             7081
Bhopal                 6587
Shillong               4762
Kochi                  3719
Ernakulam              3354
Aizawl                 2528
Name: count, dtype: int64

In [152]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for col in data.select_dtypes(include='object').columns:
    data[col] = le.fit_transform(data[col].astype(str))

data

,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,Year,Month,Day,Hour,Minute
680,0,80.47,84.90,1.42,21.90,20.65,22.83,1.42,32.26,46.71,0.0,0.0,2.07,288.0,2,2015,1,29,9,0
681,0,87.80,84.90,2.03,19.87,22.22,22.83,2.03,78.95,21.88,0.0,0.0,2.13,181.0,1,2015,1,29,10,0
682,0,90.53,84.90,1.72,20.11,22.12,22.83,1.72,95.86,67.67,0.0,0.0,3.45,182.0,1,2015,1,29,11,0
683,0,83.53,84.90,0.75,16.35,16.48,22.83,0.75,44.91,88.92,0.0,0.0,3.25,182.0,1,2015,1,29,12,0
684,0,68.40,84.90,0.58,13.73,12.50,22.83,0.58,34.57,116.75,0.0,0.0,2.85,179.0,1,2015,1,29,13,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
707870,25,9.50,36.00,2.75,25.57,15.85,4.57,0.62,1.85,27.75,0.0,0.0,0.00,51.0,3,2020,6,30,20,0
707871,25,17.25,49.25,3.62,33.20,20.62,3.78,0.76,2.02,25.58,0.0,0.0,0.00,51.0,3,2020,6,30,21,0
707872,25,36.00,71.00,2.20,30.80,18.20,3.67,0.58,1.77,26.15,0.0,0.0,0.00,50.0,0,2020,6,30,22,0
707873,25,15.75,63.00,1.02,28.90,16.00,3.80,0.49,0.75,15.82,0.0,0.0,0.00,50.0,0,2020,6,30,23,0
707874,25,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,0.0,0.0,0.00,50.0,0,2020,7,1,0,0

In [153]:
data.to_csv("eda_dataset.csv", index=False)

In [154]:
data.head(10)

,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,Year,Month,Day,Hour,Minute
680,0,80.47,84.9,1.42,21.90,20.65,22.83,1.42,32.26,46.71,0.0,0.0,2.07,288.0,2,2015,1,29,9,0
681,0,87.80,84.9,2.03,19.87,22.22,22.83,2.03,78.95,21.88,0.0,0.0,2.13,181.0,1,2015,1,29,10,0
682,0,90.53,84.9,1.72,20.11,22.12,22.83,1.72,95.86,67.67,0.0,0.0,3.45,182.0,1,2015,1,29,11,0
683,0,83.53,84.9,0.75,16.35,16.48,22.83,0.75,44.91,88.92,0.0,0.0,3.25,182.0,1,2015,1,29,12,0
684,0,68.40,84.9,0.58,13.73,12.50,22.83,0.58,34.57,116.75,0.0,0.0,2.85,179.0,1,2015,1,29,13,0
685,0,67.57,84.9,0.63,15.84,15.12,22.83,0.63,27.26,82.96,0.0,0.0,2.67,176.0,1,2015,1,29,14,0
686,0,61.13,84.9,0.43,14.07,12.90,22.83,0.43,34.47,106.88,0.0,0.0,0.78,173.0,1,2015,1,29,15,0
687,0,63.43,84.9,0.45,12.38,10.83,22.83,0.45,40.32,82.54,0.0,0.0,1.75,171.0,1,2015,1,29,16,0
688,0,54.37,84.9,0.72,14.00,13.38,22.83,0.72,35.77,73.54,0.0,0.0,0.42,167.0,1,2015,1,29,17,0
689,0,49.20,84.9,0.53,20.64,22.13,22.83,0.53,27.72,143.96,0.0,0.0,0.63,169.0,1,2015,1,29,18,0